name: pluginmanager
version: 2.3
main: me.burn38.pluginmanager.PluginManagerMain
author: [burn38]
commands:
   plm:
        description: "[pluginmanager] Use /plm help to get more informations."
        usage: "[pluginmanager] Type /plm help to get more help."